version: '3.8'

services:
  backend:
    build: ./server
    container_name: mern-backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://cloud_lab_user:thaisang@cluster0.msban3h.mongodb.net/mern-demo?retryWrites=true&w=all
      - PORT=5000

  frontend:
    build: ./client
    container_name: mern-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
